### ISSUE TITLE
Error on voluntary_share website subscription

### ISSUE THREAD

**Issue by juan-pe** [somcomunitats-coop/odoo-ec#40]
***In GitLab by @konykon on Dec 5, 2023, 15:31 GMT+1:***

```
Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/http.py", line 802, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 908, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/pyenv/versions/odoo/lib/python3.7/site-packages/odoo/addons/energy_communities/controllers/website_subscription_voluntary_share.py", line 79, in display_voluntary_share_page
    _("This company doesn't have a voluntary product share selected.")
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/http.py", line 802, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 908, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/pyenv/versions/odoo/lib/python3.7/site-packages/odoo/addons/energy_communities/controllers/website_subscription_voluntary_share.py", line 79, in display_voluntary_share_page
    _("This company doesn't have a voluntary product share selected.")
UserWarning: Esta empresa no tiene una participación de producto voluntaria seleccionada.
```

Cuando intentas abrira la siguiente pagina https://erp-prod.somcomunitats.coop/voluntary_share salta este error aunque este configurado el campo voluntary_share_id.

Creo que es porque no coge bien el company_id propongo cambiar la assignación en la linea 69 a `company_id = request.env.company`
https://git.coopdevs.org/coopdevs/comunitats-energetiques/odoo-ce/-/blob/14.0/energy_communities/controllers/website_subscription_voluntary_share.py?ref_type=heads#L69
y en la linea 72 a `"company_id": company_id,`
https://git.coopdevs.org/coopdevs/comunitats-energetiques/odoo-ce/-/blob/14.0/energy_communities/controllers/website_subscription_voluntary_share.py?ref_type=heads#L69

*Migrated from GitLab: https://git.coopdevs.org/coopdevs/comunitats-energetiques/odoo-ce/-/issues/40*

**Comment by juan-pe** [comment]
***In GitLab by @konykon on Dec 5, 2023, 15:32 GMT+1:***

created branch [`40-error-on-voluntary_share-website-subscription`](/coopdevs/comunitats-energetiques/odoo-ce/-/compare/14.0...40-error-on-voluntary_share-website-subscription) to address this issue
